### ISSUE TITLE
Migrate zip code database

### ISSUE THREAD

**Issue by benjamin-chan** [chse-ohsu/PublicUseData#2]
Gist is here: https://gist.github.com/70d8dffb1e02d17e5fb0.git

**Comment by benjamin-chan** [comment]
Gist is here: https://gist.github.com/70d8dffb1e02d17e5fb0.git

**Comment by benjamin-chan** [comment]
Add great-circle-distance calculation: http://www.inside-r.org/packages/cran/geosphere/docs/distHaversine

**Comment by renfrst** [comment]
Done!
