### ISSUE TITLE
Stata code to import BETOS

### ISSUE THREAD

**Issue by benjamin-chan** [chse-ohsu/PublicUseData#7]
See https://github.com/chse-ohsu/PublicUseData/tree/master/BETOS

> From: John McConnell 
> Sent: Tuesday, July 05, 2016 12:53 PM
> To: Benjamin Chan
> Subject: data wish list/questions
> 
> 1.       Is there a BETOS code in Stata format?

**Comment by chrisjc73** [comment]
Wrote Stata code to read in 2014 BETOS text file, add aggregate category variable, and save as .dta.

Code file is in CHSE PublicDataUse repository (convertBetos14toStata.do) 
Resulting file is saved here ("E:\Share\LookupTablesAndCrosswalks\BETOS\betpuf14\betpuf14.dta")

**Comment by benjamin-chan** [comment]
See 6f308c562203a5053f532c465b71f914dd19bb8d
